## renders to docs
on:
  schedule:
    - cron: '50 8 * * *'

name: Render each day

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install jupyter
        run: pip install jupyter -y

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: test
